config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :registrations => "registrations" }
  root "homes#index"
  resources :courses

  get "/attendances" => "attendances#index", as: :student_attendance_index
  post "/attendances" => "attendances#create", as: :student_attendance_create
  post "/attendances/checkin" => "attendances#checkin", as: :student_attendance_checkin
  patch "/attendances/mentor/set_pass/:id" => "attendances#set_pass", as: :mentor_set_pass
  patch "/attendances/mentor/assign_attendance" => "attendances#set_status", as: :mentor_set_attendance_status
  patch "/attendances/mentor/batch_assign_attendance" => "attendances#batch_set_status", as: :mentor_batch_set_attendance_status
  patch "/attendances/mentor/approve_all" => "attendances#approve_all", as: :mentor_approve_all
  post "/attendances/mentor/assign_attendance" => "attendances#set_status"
  post "/attendances/mentor/approve_absence/:id" => "attendances#approve", as: :mentor_attendance_approve
  post "/attendances/mentor/reject_absence/:id" => "attendances#reject", as: :mentor_attendance_reject
  get "/attendances/mentor" => "attendances#mentor_index", as: :mentor_attendance_index
  get "/attendances/jmentor/:id" => "attendances#mentor_show", as: :junior_mentor_attendance
  get "/attendances/smentor/:id" => "attendances#mentor_show_senior", as: :senior_mentor_attendance
  get "/attendances/:id" => "attendances#show", as: :student_attendance

  resources :sections
  get "/sections/make-switch/:old_id/:new_id" => "sections#make_switch", as: :make_switch
  get "/sections/drop/:enroll_id" => "sections#drop", as: :drop_section

  resources :enrollments
  post "/enrollments/new" => "enrollments#create"
  patch "/enrollments/:id/edit" => "enrollments#update"
  delete "/enrollments/delete/:id" => "enrollments#destroy_admin", as: :admin_destroy_enroll
  get "/offers/:id" => "offers#show", as: :offer
  get "/new_offer" => "offers#new", as: :new_offer
  post "/offers" => "offers#create"
  delete "/offers/delete/enrollment/:id" => "offers#destroy", as: :delete_offer
  post "/create_response" => "offers#create_response", as: :create_response
  get "/enrollments/:id/switch-section" => "enrollments#switch_section", as: :switch_section

  delete "/comments/:id" => "comments#destroy", as: :delete_comment
  delete "/replies/:id" => "replies#destroy", as: :delete_reply
  post "/replies/accept/:id" => "replies#accept", as: :accept_reply
  post "/replies/deny/:id" => "replies#deny", as: :deny_reply

  get "/users/contract/:id" => "users#contract", as: :contract
  post "/users/sign-contract/:id" => "users#sign_contract", as: :sign_contract

  resources :jenrolls
  post "/jenrolls/mentorenrollredirect" => "jenrolls#mentor_enroll_redirect", as: :mentor_enroll_redirect
  get "/jenrolls/mentorenroll/:course_id" => "jenrolls#mentor_enroll", as: :mentor_enroll
  post "/jenrolls/new" => "jenrolls#create"
  patch "/jenrolls/:id/edit" => "jenrolls#update"
  get "/jenrolls/:id/switch" => "jenrolls#switch", as: :jenroll_switch
  patch "/jenrolls/:id/switch" => "jenrolls#update_switch", as: :jenroll_update_switch
  get "/jenrolls/:id/roster" => "jenrolls#roster", as: :jenroll_roster
  delete "/jenrolls/:id/templocation" => "jenrolls#destroy_temp_location", as: :jenroll_destroy_temp_location
  delete "/jenrolls/:id/temptime" => "jenrolls#destroy_temp_time", as: :jenroll_destroy_temp_time

  resources :senrolls
  patch "/senrolls/:id/edit" => "senrolls#update"
  get "/senrolls/:id/switch" => "senrolls#switch", as: :senroll_switch
  patch "/senrolls/:id/switch" => "senrolls#update_switch", as: :senroll_update_switch
  get "/senrolls/:id/roster" => "senrolls#roster", as: :senroll_roster
  delete "/senrolls/:id/templocation" => "senrolls#destroy_temp_location", as: :senroll_destroy_temp_location
  delete "/senrolls/:id/temptime" => "senrolls#destroy_temp_time", as: :senroll_destroy_temp_time

  match "/admin/students" => "admins#index", as: :students_index, via: [:get, :post]
  get "/admin/mentors" => "admins#mentor_index", as: :mentors_index
  get "/admin/new-student" => "admins#new_student", as: :admin_new_student
  post "/admin/create-student" => "admins#create_student", as: :admin_create_student
  get "/admin/students/:id" => "admins#edit_student", as: :admin_edit_student
  patch "/admin/students/:id" => "admins#update_student", as: :admin_update_student
  post "/admin/students/add_course/:user_id" => "admins#add_course", as: :admin_add_course
  get "/admin/courses" => "courses#admin_index", as: :admin_course_index
  post "/admin/send_email" => "admins#send_email", as: :admin_send_email
  get "/settings" => "settings#index",  as: :settings
  post "/settings" => "settings#update"
  get "/admin/manage_sections" => "admins#manage_sections", as: :manage_sections
  get "/admin/manage_attendance" => "admins#manage_attendance", as: :manage_attendance
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  get "/settings/announcement_edit" => "announcements#edit", as: :announcement_edit
  patch "/settings/announcement_edit" => "announcements#update", as: :announcement_update
  
  get "/admin/manage_section/add/:id" => "admins#new_student_to_section", as: :new_student_to_section
  post "/admin/manage_section/add/:id" => "admins#add_student_to_section"
  post "/admin/manage_sections/drop/:id" => "admins#drop_student_from_section", as: :drop_student_from_section

end

app/models/jenroll.rb
class Jenroll < ActiveRecord::Base
	belongs_to :user
	belongs_to :course
	belongs_to :section
	has_many :attendances, dependent: :destroy
	has_many :senrolls, :through => :mentorjoins
	has_many :mentorjoins

	def getStudents()
		@section = self.section
		users = []
		@section.enrolls.each do |enroll|
			users << enroll.user
		end
		return users
	end
end

app/controllers/jenrolls_controller.rb
class JenrollsController < ApplicationController
    before_filter :check_logged_in
    before_filter :check_mentor_enroll, :only => [:mentor_enroll_redirect]
    before_filter :check_create, :only => [:create]
    before_filter :check_jenroll, :only => [:destroy, :switch, :update_switch, :edit, :update, :destroy_temp_location, :destroy_temp_time, :roster]
    before_filter :check_update_switch, :only => [:update_switch]

	def new
        if not current_user.mentor_verified
            flash[:notice] = "Please agree to the contract to be a mentor!"
            redirect_to contract_path(current_user)
            return
        end
        @courses = Course.all
	end

    def mentor_enroll_redirect
        @course = Course.find(params[:course_id])
        redirect_to mentor_enroll_path(course_id: @course.id)
    end

	def mentor_enroll
		@course = Course.find(params[:course_id])
		@sections = Section.getSectionsWithoutMentor(@course)
	end

    def create
	    password = params[:pass]
	    @section = Section.find(params[:section_id])
	    @course = @section.course
		if password == @course.password
            if params.has_key?("sm?")
                @senroll = Senroll.new
                if (@section.assignMentor(@senroll) == nil)
                    flash[:notice] = "Someone has already taken this section."
                    redirect_to root_path
                    return
                end
                current_user.senrolls << @senroll
                @course.senrolls << @senroll
            else
                @jenroll = Jenroll.new
                if (@section.assignMentor(@jenroll) == nil) 
                    flash[:notice] = "Someone has already taken this section."
                    redirect_to root_path
                    return
                end
                current_user.jenrolls << @jenroll
                @course.jenrolls << @jenroll
            end
			flash[:notice] = "You have been signed up as a mentor!"
			redirect_to root_path
		else 
	  		flash[:notice] = "Invalid mentor password!"
	  		redirect_to :back
	  	end
    end
    def destroy
    	@jenroll = Jenroll.find(params[:id])
    	@jenroll.destroy
    	flash[:notice] = "You are no longer mentoring that section."
    	redirect_to root_path
    end

    def switch
        @jenroll = Jenroll.find(params[:id])
        @course = Course.find(@jenroll.course_id)
        @sections = Section.getSectionsWithoutMentor(@course)
    end

    def update_switch
        @jenroll = Jenroll.find(params[:id])
        @section = @jenroll.section
        @section.temp_start = nil
        @section.temp_end = nil
        @section.temp_location = nil
        @section.temp_date = ""
        @section.save
        if @jenroll.update_attributes(jenroll_params)
            flash[:notice] = "Switched your mentoring section!"
            redirect_to root_path
        else
            flash[:notice] = "Something went wrong. Please try again later."
            redirect_to root_path
        end
    end

    def edit
    	@jenroll = Jenroll.find(params[:id])
    	@section = Section.find(@jenroll.section_id)
    end
    def update
    	@jenroll = Jenroll.find(params[:id])
        @section = Section.find(@jenroll.section_id)
        @new_section = Section.new(jenroll_section_params)
        time_change = false
        location_change = false
        if @new_section.temp_start != nil and @new_section.temp_end != nil and @new_section.temp_date != ""
            if params["makeDefaultTime?"] and (Setting.find_by(name: 'default_switching').value == "1" or current_user.admin)
                @section.start = @new_section.temp_start
                @section.end = @new_section.temp_end
                @section.date = @new_section.temp_date
            end
            @section.temp_start = @new_section.temp_start
            @section.temp_end = @new_section.temp_end
            @section.temp_date = @new_section.temp_date
            time_change = true
        elsif @new_section.temp_start != nil or @new_section.temp_end != nil or @new_section.temp_date != ""
            #missing fields
            missing_fields = []
            if @new_section.temp_start == nil
                missing_fields << "start"
            end
            if @new_section.temp_end == nil
                missing_fields << "end"
            end
            if @new_section.temp_date == ""
                missing_fields << "date"
            end
            missing_field_string = String.new(missing_fields[0])
            (1...missing_fields.size).each do |i|
                missing_field_string << ", #{String.new(missing_fields[i])}"
            end
            if missing_fields.size > 1
                flash[:notice] = "Missing fields #{missing_field_string} for new section."
            else
                flash[:notice] = "Missing field #{missing_field_string} for new section."
            end
            redirect_to edit_jenroll_path(@jenroll)
            return
        end

        if @new_section.temp_location != ""
            if params["makeDefaultLocation?"] and (Setting.find_by(name: 'default_switching').value == "1" or current_user.admin)
                @section.location = @new_section.temp_location
            end
            @section.temp_location = @new_section.temp_location
            location_change = true
        end
        if params["notify?"] and (location_change or time_change)
            #mail
            users = []
            users << User.find(@jenroll.user_id)
            @section.enrolls.each do |enroll|
                users << User.find(enroll.user_id)
            end
            users.each do |user|
                #uncomment when working
                UserMailer.timeloc_change_email(user, @section, time_change, location_change).deliver
            end
        end
    	if @section.save
    		flash[:notice] = "Your mentor settings have been saved!"
    		redirect_to root_path
    	else
    		flash[:notice] = "Something went wrong. Please try again later."
    		redirect_to root_path
    	end
    end

    def destroy_temp_location
        @jenroll = Jenroll.find(params[:id])
        @section = Section.find(@jenroll.section_id)
        @user = @jenroll.user
        @section.temp_location = nil
        UserMailer.location_remove_email(@user, @section).deliver
        if @section.save
            flash[:notice] = "Temporary location change removed."
        else
            flash[:notice] = "Something went wrong. Please try again later."
        end
        redirect_to edit_jenroll_path(@jenroll)
    end

    def destroy_temp_time
        @jenroll = Jenroll.find(params[:id])
        @section = Section.find(@jenroll.section_id)
        @user = @jenroll.user
        @section.temp_start = nil
        @section.temp_end = nil
        @section.temp_date = ""
        UserMailer.time_remove_email(@user, @section).deliver
        if @section.save
            flash[:notice] = "Temporary time change removed."
        else
            flash[:notice] = "Something went wrong. Please try again later."
        end
        redirect_to edit_jenroll_path(@jenroll) 
    end

    def roster
    	@jenroll = Jenroll.find(params[:id])
    	@students = @jenroll.getStudents()
        @email_list = ""
        @students.each_with_index do |student, i| 
            if i == 0
                @email_list << "#{student.name} <#{student.email}>"
            else
                @email_list << ", #{student.name} <#{student.email}>"
            end
        end
    end

    private
	def jenroll_params
		params.require(:jenroll).permit(:section_id)
	end

    private
    def jenroll_section_params
        params.require(:section).permit(:temp_start, :temp_end, :temp_location, :temp_date)
    end

    #before filters
    private
    def check_jenroll
        if not params[:id] or not Jenroll.exists?(params[:id]) or not (check_enrollment(Jenroll.find(params[:id])) or current_user.admin)
            flash[:notice] = "You do not have permission to access that page."
            redirect_to root_path
        end
    end

    private
    def check_mentor_enroll
        if not params[:course_id]
            flash[:notice] = "Please choose a course."
            redirect_to new_jenroll_path
        end
    end

    private
    def check_create
        if params[:pass] == ""
            flash[:notice] = "Please enter in the password."
            redirect_to :back
            return
        end
        if not params[:section_id]
            flash[:notice] = "Please choose a section."
            redirect_to :back
            return
        end
    end

    private
    def check_update_switch
        if params[:jenroll]
            jenroll = Jenroll.new(jenroll_params)
            if jenroll.section_id and Section.exists?(jenroll.section_id)
                return
            end
        end
        flash[:notice] = "Please choose a section."
        redirect_to :back
    end
end

app/helpers/jenrolls_helper.rb
module JenrollsHelper
end

app/views/jenrolls/edit.html.erb
<h2>Mentor Settings For Section</h2>
<%= form_for @section, url: edit_jenroll_path(@jenroll.id) do |f|%>
    <div class"form-group">
        <%= hidden_field_tag :id, @section.id %>
    </div>
    <div class = "row">
        <div class = "col-sm-12">
            <div class="panel panel-default">
              <!-- Default panel contents -->
              <div class="panel-heading"><h4>Make a Temporary Time Change</h4></div>
              <div class="panel-body">
                <% if @section.temp_start == nil %>
                    <h6>Current time from <%= @section.start.strftime("%I:%M %p") %> to <%= @section.end.strftime("%I:%M %p") %> on <%= @section.date %>.</h6>
                <% elsif @section.temp_start == @section.start and @section.temp_end == @section.end and @section.temp_date == @section.date %>
                    <h6>Default time of section recently changed to be from <%= @section.start.strftime("%I:%M %p") %> to <%= @section.end.strftime("%I:%M %p") %> on <%= @section.date %>.</h6>
                <% else %>
                    <h6>Temporary time set to be from <%= @section.temp_start.strftime("%I:%M %p") %> to <%= @section.temp_end.strftime("%I:%M %p") %> on <%= @section.temp_date %>.</h6>
                <% end %>

                <div class="form-group">
                    <%= f.label :start %>
                    <div class='input-group date' id='starttimepicker'>
                        <% if @section.temp_start != nil %>
                            <%= f.text_field(:temp_start, class:"form-control", :value => @section.temp_start.strftime("%I:%M %p")) %>
                        <% else %>
                            <%= f.text_field(:temp_start, class:"form-control") %>
                        <% end %>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-time"></span>
                        </span>
                    </div>
                </div>
                <div class="form-group">
                    <%= f.label :end %>
                    <div class='input-group date' id='endtimepicker'>
                        <% if @section.temp_start != nil %>
                            <%= f.text_field(:temp_end, class:"form-control", :value => @section.temp_end.strftime("%I:%M %p")) %>
                        <% else %>
                            <%= f.text_field(:temp_end, class:"form-control") %>
                        <% end %>
                        <span class="input-group-addon">
                            <span class="glyphicon glyphicon-time"></span>
                        </span>
                    </div>
                </div>
                <script type="text/javascript">
                    $(function () {
                        $('#starttimepicker').datetimepicker({
                            format: 'LT'
                        });
                        $('#endtimepicker').datetimepicker({
                            format: 'LT'
                        });
                    });
                </script>
                <div class="form-group">
                    <%= f.label :date, "Day of the week" %>
                    <br>
                    <%= f.select(:temp_date, options_for_select([["None Selected", ""],['Monday', 'Monday'], ['Tuesday', 'Tuesday'], ['Wednesday', 'Wednesday'], ['Thursday', 'Thursday'], ["Friday", "Friday"]], @section.temp_date)) %>
                </div>
              </div>

              <div class="panel-footer">
                <% if Setting.find_by(name: 'default_switching').value == "1" or current_user.admin %>
                    <label><%= check_box_tag 'makeDefaultTime?'%> Make this the default time/date?</label>
                <% end %>
                <% if @section.temp_start != nil and not (@section.temp_start == @section.start and @section.temp_end == @section.end and @section.temp_date == @section.date) %>
                    <br>
                    <%= link_to '<i class="fa fa-trash-o"></i> Revert Time to Default'.html_safe, jenroll_destroy_temp_time_path(@jenroll), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?"}%>
                <% end %>
              </div>
            </div>
        </div>
        <div class = "col-sm-12">
            <div class="panel panel-default">
              <!-- Default panel contents -->
              <div class="panel-heading"><h4>Make a Temporary Location Change</h4></div>
              <div class="panel-body">
                <% if @section.temp_location == nil %>
                    <h6>Current location at <%= @section.location %>.</h6>
                <% elsif @section.temp_location == @section.location  %>
                    <h6>Default location of section recently changed to be <%= @section.location %>.</h6>
                <% else %>
                    <h6>Temporary location set to be <%= @section.temp_location %>.</h6>
                <% end %>
                <div class="form-group">
                    <%= f.label :location %>
                    <%= f.text_field(:temp_location, class:"form-control") %> 
                </div>
              </div>

              <div class="panel-footer">
                <% if Setting.find_by(name: 'default_switching').value == "1" or current_user.admin %>
                    <label><%= check_box_tag 'makeDefaultLocation?'%> Make this the default location?</label>
                    <br>
                <% end %>
                <% if @section.temp_location != nil and @section.temp_location != @section.location %>
                    <br>
                    <%= link_to '<i class="fa fa-trash-o"></i> Remove Location to Default'.html_safe, jenroll_destroy_temp_location_path(@jenroll), class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure?"}%>
                <% end %>
              </div>
            </div>
            <div style = "text-align:center; padding-top:20px">
                <label><%= check_box_tag 'notify?', 1, {:checked => "checked"} %> Notify your students of your changes via email?</label>
                <br>
                <%= f.submit "Update Settings", class: "btn btn-success" %>
                <%= link_to "Cancel", root_path, class: "btn btn-default" %>
            </div>
        </div>
    </div>
<% end %>

app/views/jenrolls/mentor_enroll.html.erb
<h3>Choose an available section to mentor</h3>
<%= form_tag(new_jenroll_path) do |f| %>
  <div class="form-group">
    <label for="mentor-pass">Password</label>
    <div class = "alert alert-info" style = "margin-top:0px">
       <p><i class = "fa fa-question-circle"></i> <b>What password?</b></p>
       <p> This is the mentor password you have received in your email in order to sign up as a mentor. It is not your password or this account.</p>

    </div>
    <%= password_field_tag :pass, nil, :class=> "form-control", :id => "mentor-pass", :placeholder => "Mentor Password"%>
  </div>


  <label><%= check_box_tag 'sm?'%> Check if enrolling as a senior mentor.</label>
  <table class="table">
    <thead>
      <tr>
        <th>  </th>
        <th> Section Name </th>
        <th> Day </th>
        <th> Time </th>
        <th> Location </th>
      </tr>
    </thead>
    <tbody>
      <% @sections.each do |section| %>
        <tr>
          <td> <%= radio_button_tag :section_id, section.id %> </td>
          <td> <%= section.name %> </td>
          <td> <%= section.date %> </td>
          <td> <% if section.start and section.end %>
            <%= section.start.strftime("%I:%M %p") %>-<%= section.end.strftime("%I:%M %p") %>
          <% end %> </td>
          <td> <%= section.location %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <div class = "actions" style = "margin-top: 10px">
    <%= button_tag(type: 'submit', class: "btn btn-success") do %>
     <i class='fa fa-plus'></i> Add
    <% end %>
  </div>
<% end %>

app/views/jenrolls/new.html.erb
<h3>Choose a course</h3>
<%= form_tag(mentor_enroll_redirect_path) do |f| %>

  <table class="table">
    <thead>
      <tr>
        <th>  </th>
        <th> Course Name </th>
        <th> Semester </th>
      </tr>
    </thead>
    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td> <%= radio_button_tag :course_id, course.id %> </td>
          <td> <%= course.course_name %> </td>
          <td> <%= course.semester %> <%= course.year %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>
  <div class = "actions" style = "margin-top: 10px">
    <%= button_tag(class: "btn btn-success") do %>
     <i class='fa fa-plus'></i> Add
    <% end %>
  </div>

<% end %>

app/views/jenrolls/roster.html.erb
<div class = "roster">
	<% if @students.size > 0 %>
		<h3>Your Students</h3>
		<ul class="list-group">
		<% @students.each do |student| %>
		  <li class="list-group-item">
		    <span class="badge"><%=student.email%></span>
		    <%=student.name %>
		  </li>
		<% end %>
		</ul>
			
				
		<h3>Email List</h3>
		<div class="input-group input-group-lg">
		  <span class="input-group-addon" id="sizing-addon1"><i class="fa fa-envelope"></i></span>
		  <input type="text" class="form-control" value="<%=@email_list%>" onclick="this.select()" aria-describedby="sizing-addon1">
		</div>
	<% else %>
		<h3>No Students</h3>
	<% end %>
</div>

app/views/jenrolls/switch.html.erb
<h3>Choose a section</h3>
<%= form_for @jenroll, url: jenroll_update_switch_path(@jenroll.id) do |f| %>

      <table class="table">
        <thead>
          <tr>
            <th>  </th>
            <th> Section # </th>
            <th> Day </th>
            <th> Time </th>
            <th> # Enrolled </th>
            <th> Location </th>
          </tr>
        </thead>
        <tbody>
        <% counter = 0%>
          <% @sections.each do |section| %>
            <% section_limit = section.getLimit() %>
            <% counter += 1%>
            <tr >
              <% if section.getMentor() != nil %>
                <td> <%= f.radio_button :section_id, section.id, :disabled => true %> </td>
              <% else %>
                <td> <%= f.radio_button :section_id, section.id %> </td>
              <% end %>
              <td> <%= section.name %> </td>
              <td> <%= section.date %> </td>
              <td> <% if section.start and section.end %>
                <%= section.start.strftime("%I:%M %p") %>-<%= section.end.strftime("%I:%M %p") %>
                <% end %> </td>
              <td> <%= section.enrolls.size %> out of <%= section_limit %> </td>
              <td> <%= section.location %> </td>
            </tr>
            <% end %>
          <% if counter == 0 %>
            There are no sections available. Check back tomorrow, and there might be room!
          <% end %>
        </tbody>
      </table>
  <% if counter > 0 %>
  <%= f.submit "Switch section", class: "btn btn-success" %>
  <% end %>
<% end %>