config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :registrations => "registrations" }
  root "homes#index"
  resources :courses

  get "/attendances" => "attendances#index", as: :student_attendance_index
  post "/attendances" => "attendances#create", as: :student_attendance_create
  post "/attendances/checkin" => "attendances#checkin", as: :student_attendance_checkin
  patch "/attendances/mentor/set_pass/:id" => "attendances#set_pass", as: :mentor_set_pass
  patch "/attendances/mentor/assign_attendance" => "attendances#set_status", as: :mentor_set_attendance_status
  patch "/attendances/mentor/batch_assign_attendance" => "attendances#batch_set_status", as: :mentor_batch_set_attendance_status
  patch "/attendances/mentor/approve_all" => "attendances#approve_all", as: :mentor_approve_all
  post "/attendances/mentor/assign_attendance" => "attendances#set_status"
  post "/attendances/mentor/approve_absence/:id" => "attendances#approve", as: :mentor_attendance_approve
  post "/attendances/mentor/reject_absence/:id" => "attendances#reject", as: :mentor_attendance_reject
  get "/attendances/mentor" => "attendances#mentor_index", as: :mentor_attendance_index
  get "/attendances/jmentor/:id" => "attendances#mentor_show", as: :junior_mentor_attendance
  get "/attendances/smentor/:id" => "attendances#mentor_show_senior", as: :senior_mentor_attendance
  get "/attendances/:id" => "attendances#show", as: :student_attendance

  resources :sections
  get "/sections/make-switch/:old_id/:new_id" => "sections#make_switch", as: :make_switch
  get "/sections/drop/:enroll_id" => "sections#drop", as: :drop_section

  resources :enrollments
  post "/enrollments/new" => "enrollments#create"
  patch "/enrollments/:id/edit" => "enrollments#update"
  delete "/enrollments/delete/:id" => "enrollments#destroy_admin", as: :admin_destroy_enroll
  get "/offers/:id" => "offers#show", as: :offer
  get "/new_offer" => "offers#new", as: :new_offer
  post "/offers" => "offers#create"
  delete "/offers/delete/enrollment/:id" => "offers#destroy", as: :delete_offer
  post "/create_response" => "offers#create_response", as: :create_response
  get "/enrollments/:id/switch-section" => "enrollments#switch_section", as: :switch_section

  delete "/comments/:id" => "comments#destroy", as: :delete_comment
  delete "/replies/:id" => "replies#destroy", as: :delete_reply
  post "/replies/accept/:id" => "replies#accept", as: :accept_reply
  post "/replies/deny/:id" => "replies#deny", as: :deny_reply

  get "/users/contract/:id" => "users#contract", as: :contract
  post "/users/sign-contract/:id" => "users#sign_contract", as: :sign_contract

  resources :jenrolls
  post "/jenrolls/mentorenrollredirect" => "jenrolls#mentor_enroll_redirect", as: :mentor_enroll_redirect
  get "/jenrolls/mentorenroll/:course_id" => "jenrolls#mentor_enroll", as: :mentor_enroll
  post "/jenrolls/new" => "jenrolls#create"
  patch "/jenrolls/:id/edit" => "jenrolls#update"
  get "/jenrolls/:id/switch" => "jenrolls#switch", as: :jenroll_switch
  patch "/jenrolls/:id/switch" => "jenrolls#update_switch", as: :jenroll_update_switch
  get "/jenrolls/:id/roster" => "jenrolls#roster", as: :jenroll_roster
  delete "/jenrolls/:id/templocation" => "jenrolls#destroy_temp_location", as: :jenroll_destroy_temp_location
  delete "/jenrolls/:id/temptime" => "jenrolls#destroy_temp_time", as: :jenroll_destroy_temp_time

  resources :senrolls
  patch "/senrolls/:id/edit" => "senrolls#update"
  get "/senrolls/:id/switch" => "senrolls#switch", as: :senroll_switch
  patch "/senrolls/:id/switch" => "senrolls#update_switch", as: :senroll_update_switch
  get "/senrolls/:id/roster" => "senrolls#roster", as: :senroll_roster
  delete "/senrolls/:id/templocation" => "senrolls#destroy_temp_location", as: :senroll_destroy_temp_location
  delete "/senrolls/:id/temptime" => "senrolls#destroy_temp_time", as: :senroll_destroy_temp_time

  match "/admin/students" => "admins#index", as: :students_index, via: [:get, :post]
  get "/admin/mentors" => "admins#mentor_index", as: :mentors_index
  get "/admin/new-student" => "admins#new_student", as: :admin_new_student
  post "/admin/create-student" => "admins#create_student", as: :admin_create_student
  get "/admin/students/:id" => "admins#edit_student", as: :admin_edit_student
  patch "/admin/students/:id" => "admins#update_student", as: :admin_update_student
  post "/admin/students/add_course/:user_id" => "admins#add_course", as: :admin_add_course
  get "/admin/courses" => "courses#admin_index", as: :admin_course_index
  post "/admin/send_email" => "admins#send_email", as: :admin_send_email
  get "/settings" => "settings#index",  as: :settings
  post "/settings" => "settings#update"
  get "/admin/manage_sections" => "admins#manage_sections", as: :manage_sections
  get "/admin/manage_attendance" => "admins#manage_attendance", as: :manage_attendance
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  get "/settings/announcement_edit" => "announcements#edit", as: :announcement_edit
  patch "/settings/announcement_edit" => "announcements#update", as: :announcement_update
  
  get "/admin/manage_section/add/:id" => "admins#new_student_to_section", as: :new_student_to_section
  post "/admin/manage_section/add/:id" => "admins#add_student_to_section"
  post "/admin/manage_sections/drop/:id" => "admins#drop_student_from_section", as: :drop_student_from_section

end

app/views/admins/_section.html.erb
<strong> <%= section.name %> </strong>
<%= link_to "<i class='fa fa-pencil'></i>".html_safe, edit_section_path(section) %>
<%= link_to "<i class='fa fa-trash'></i>".html_safe, section_path(section), :method => :delete,data: { confirm: "Are you sure you want to delete the section?"} %> <br>
<i class="fa fa-user"></i> <%= section.getMentorName() %> <br>
<i class="fa fa-map-marker"></i>
    <% if section.temp_location == nil %>
        <%= section.location %>
    <% else %>
        <%= section.temp_location %>
    <% end %>
    <br> 
<i class="fa fa-envelope"></i> <%= mail_to(section.getMentorEmail(), (section.getMentorEmail() ? section.getMentorEmail().truncate(23)  : "")) %><br>
<% if section.start and section.end %>
     <i class="fa fa-clock-o"></i> <%= section.start.strftime("%I:%M %p") %>-<%= section.end.strftime("%I:%M %p") %> <br>
<% end %>

<strong> Students </strong> <%= link_to "<i class='fa fa-plus'></i>".html_safe, new_student_to_section_path(section) %><br>
<%= section.enrolls.size %>/<%= section.getLimit %> enrolled <br>
<% section.enrolls.each do |enroll| %>
  <%= link_to "<i class='fa fa-times'></i>".html_safe, drop_student_from_section_path(enroll), :method => :post,data: { confirm: "Are you sure you want to drop the student?"}%> 
  <%= User.find(enroll.user.id).name %> - <%= enroll.attendances.select {|x| x.approved? or x.excused? }.count %>
<br>
<% end %>

app/views/admins/edit_student.html.erb
<div class="panel panel-default">
    <div class="panel-heading">Update user</div>
    <div class="panel-body">
    <%= form_for @student, url: admin_update_student_path do |f|%>
        <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field(:name, class:"form-control") %> 
        </div>
     <div class="form-group">
        <%= f.label :nickname %>
        <%= f.text_field(:nickname, class:"form-control") %> 
        </div>
     <div class="form-group">
        <%= f.label :email %>
        <%= f.text_field(:email, class:"form-control") %> 
    </div>
        <div class="form-group">
        <%= f.check_box :admin %>
        <%= f.label :admin %>
        </div>
        <%= f.submit class: "btn btn-default" %>
    <% end %>
    </div>
</div>

app/views/admins/index.html.erb
<div class = "container">
    <h1>Manage Students</h1>
    <hr>
    <%= link_to "<i class='fa fa-plus'></i> Add User".html_safe, admin_new_student_path, :class => "btn btn-success" %>
    <div style = "margin-top:10px">
        <b>Total students</b>: <%= @students.length %>
    </div>
    <div>
        <b>Total course enrollments</b>: <%=  @total_course_enrollment %>
    </div>
    <div>
        <b>Total section enrollments</b>: <%=  @total_section_enrollment %>
    </div>
    <div class = "sections">
      <table class="table">
        <thead>
          <tr>
            <th> Actions </th>
            <th> Students </th>
            <th> Email </th>
          </tr>
        </thead>
        <tbody>
            <% @students.each do |student| %>
                <tr class="student-list">
                <td class="col-md-2">
                <div class="row">
                <div class="border col-xs-3">
                <a class="btn btn-success" id="add-course" data-toggle="collapse" data-tt="tooltip" title="Add Course" href="#coursecollapse<%=student.id%>" href="#" role="button"><i class="fa fa-plus"></i></a> 
                </div>
                <div class="border col-xs-3">
                <a class="btn btn-warning" id="drop-course" data-toggle="collapse" data_tt="tooltip" title="Drop Course" href="#editcollapse<%=student.id%>"  role="button"><i class="fa fa-pencil-square"></i></a>
                </div>

                <div class="border col-xs-3">
                <%= link_to '<span class="btn btn-info" id="update-user" data-toggle="tooltip" title="Update User" href="#" role="button"><i class="fa fa-user"></i></span>'.html_safe, admin_edit_student_path(student), method: :get %>
                </div>
                <div class="border col-xs-3">
                <%= link_to '<span class="btn btn-danger" id="delete-user" data-toggle="tooltip" title="Delete User" href="#" role="button"><i class="fa fa-times"></i></span>'.html_safe, admin_destroy_user_path(student), method: :delete, data: { confirm: "Are you sure you want to delete #{student.name}?" } %>
                </div>
                </div>
                </td>
                <td>
                <h4 style="">
                 <%= student.name %>
                 </h4>
                </td>
                
                <td>
                <%= student.email %>

                <%= form_tag admin_add_course_path(student) do %>
                <br />
                <div class="panel collapse panel-default" id="coursecollapse<%=student.id%>">
                    <div class="panel-heading">Add course</div>
                    <div class="panel-body">
                <%
                exclude = []
                student.enrolls.each do |e|
                    exclude << e.course_id
                end
                possible_enroll = Course.where.not(id: exclude)
                %>
                <% if possible_enroll.length > 0 %>
                    <%= fields_for "course[]", @courses do |f| %>
                        <div class="field">
                        <div class="form-group">
                        <label>Course</label>
                            <%= f.select :name, possible_enroll.collect {|p|                             
                                [ p.course_name, p.id]
                                 },{}, {prompt: "Select one", class: "form-control"}%>
                        </div>
                        </div>
                        <%= submit_tag("Add", class: "btn btn-success") %>
                    <% end %>
                <% else %>
                No courses to add.
                 <% end %>
                <% end %>
                </div>
                </div>
                <div class="collapse" id="editcollapse<%=student.id%>">
                <table class="table" >
                        <thead>
                            <tr>
                                <th></th>
                                <th>Class</th>
                                <th>Section</th>
                            </tr>
                        
                        </thead>
                    <tbody>
                <% student.enrolls.each do |enroll| %>
                    
                    <tr>
                        <td class="col-md-1">
                         <%= link_to '<span data-toggle="tooltip" data-placement="bottom" title="Drop from class" class="btn btn-danger" href="#" role="button"><i class="fa fa-trash-o"></i></span>'.html_safe, admin_destroy_enroll_path(enroll), method: :delete, data: { confirm: "Are you sure?" } %>

                        </td>
                        <td class="col-md-1"><b><%= enroll.course.course_name %></b></td>
                        <td>
                            <% if enroll.section %>
                            <span><%= enroll.section.name.chomp %></span>
                            <% else %>
                            N/A
                            <% end %>
                        </td>
                        </tr>
                    
                <% end %>
                    </tbody>
                    </table>
                    <br />
                </div>
                </td>
                </tr>  
            <% end %>
        </tbody>
        </table>
    </div>
</div>

app/views/admins/manage_attendance_old.html.erb
<div class="container">
  <h1>Manage Student Attendance</h1>
  <hr>

  <!-- 
    To Dos:
      - Toggle all students
      - Generate the right attendance link
      - Get sections to display, sort of works
        - but switching sections doesn't hold, as in links are not generated properly upon switch
        - when dropped sections 
   -->

  <div style="margin-top:10px">
    <a class="btn btn-primary" data-toggle="collapse" href="#rostercollapse"  role="button">Toggle All Students</a>
    <!-- <a class="btn btn-danger" href="#" role="button">Download as CSV</a> -->
    <br><br>
  </div>

  <div class="sections">
    <table class="table">
      <thead>
        <tr>
          <th>Attendance Status</th>
          <th>Mentors</th>
        </tr>
      </thead>

      <tbody>
        <!-- iterating through the sections and assuming the mentor will stay the same is wrong -->
        <% @sections.each do |section| %>
          <% section.enrolls.each do |enroll| %>
            <tr class="mentor-list">
              <!-- Left Column -->
              <td class="col-md-2">
                <% section.jenroll == nil ? (mentor = section.senroll) : (mentor = section.jenroll) %>
                <% course = enroll.course %>
                <% course_name = course.course_name %>
                <% if mentor != nil%>
                  <div>
                    <a class="btn btn-success" data-toggle="collapse" href="#rostercollapse<%=mentor.id%>"  href="#" role="button"><i class="fa fa-list"></i></a>
                    <a class="btn btn-warning"  data-toggle="collapse" href="#editcollapse<%=mentor.id%>"  role="button"><i class="fa fa-dashboard"></i></a>
                  </div>
                  <div>
                    <% badge_button = '<i class="fa fa-person"></i> '.html_safe + getPendingBadge(enroll).html_safe + ' Take '%>
                    <!-- Fix these -->
                    <% if section.jenroll === nil %>
                      <%= link_to badge_button.html_safe, senior_mentor_attendance_path(mentor.id), :class => "btn btn-danger" %>
                    <% else %>
                      <%= link_to badge_button.html_safe, junior_mentor_attendance_path(mentor.id), :class => "btn btn-danger" %>
                    <% end %>
                    </div>
                  </div>
                </td>
                
                <!-- Right Column -->
                <td>
                  <!-- Information -->
                  <h4><%= section.getMentorName() %></h4>
                  <%= section.getMentorEmail() %>
                  <!-- Student roster -->
                  <%= form_tag admin_add_course_path(mentor) do %>
                    <br />
                    <div class="collapse" id="rostercollapse<%=mentor.id%>">
                      <div class="roster">
                        <h5><b><%= course_name %> <%= section.name %> Students</b></h5>
                        <% if enroll.getStudents().size > 0 %>
                          <ul class="list-group">
                          <% enroll.getStudents().each do |student| %>
                            <li class="list-group-item" style="width: 75%">
                              <div style="float:left">
                                <%= student.name %>
                                <span class="badge"><%=student.email%></span>
                              </div>
                              <div style="float:right">
                                <% approved = enroll.attendances.approved.count %>
                                <% excused = enroll.attendances.excused.count %>
                                <% pending = enroll.attendances.pending.count %>
                                <span class="label label-success">Approved: <%= approved %></span>
                                <span class="label label-primary">Excused: <%= excused %></span>
                                <span class="label label-warning">Pending: <%= pending %></span>
                                <span class="label label-danger">Unexcused: 
                                  <%= enroll.getCurrentWeek() - approved - excused - pending %></span>
                              </div>
                              <br>
                            </li>
                          <% end %>
                          </ul>                                    
                        <% else %>
                          <h6>No Students</h6>
                        <% end %>
                      </div>
                    </div>
                  <!-- form_tag -->
                  <% end %>

                <!-- Section Information -->
                <div class="collapse" id="editcollapse<%=mentor.id%>">
                  <div class="panel panel-primary" style="width: 80%">
                    <div class="panel-heading">
                      <h3 class="panel-title"><i class="fa fa-book"></i> <%= course_name %> 
                      </h3>
                    </div>
                    <div class="panel-body">
                      <% curr_section = Section.find(enroll.section_id) %>
                      <h4>  <%= link_to curr_section.name, section_path(curr_section) %></h4>
                      <ul class="list-unstyled">        
                        <li><b>Mentor:</b> <%= curr_section.getMentorName() %> (<%= mail_to curr_section.getMentorEmail() %>) </li>

                        <!-- Make a temporary location change -->
                        <% if curr_section.temp_location == nil %>
                          <li><b>Location:</b> <%= curr_section.location %> </li>
                        <% elsif curr_section.temp_location == curr_section.location %>
                          <li><h4 style = "color:red;"><b>PERMANENT LOCATION:</b> <%= curr_section.location %></h4></li>
                        <% else %>
                          <li><h4 style = "color:red;"><b>TEMPORARY LOCATION:</b> <%= curr_section.temp_location %></h4></li>
                        <% end %>

                        <!-- Make a temporary time change -->
                        <% if curr_section.temp_start == nil %>
                          <li><b>Time:</b> <%=curr_section.date %> <%= curr_section.start.strftime("%I:%M %p") %>-<%= curr_section.end.strftime("%I:%M %p") %> </li>
                        <% elsif curr_section.temp_start == curr_section.start and curr_section.temp_end == curr_section.end and curr_section.temp_date == curr_section.date %>
                          <li><h4 style = "color:red;"><b>PERMANENT TIME:</b> <%=curr_section.date %> <%= curr_section.start.strftime("%I:%M %p") %>-<%= curr_section.end.strftime("%I:%M %p") %></h4></li>
                        <% else %>
                          <li><h4 style = "color:red;"><b>TEMPORARY TIME:</b> <%=curr_section.temp_date %> <%= curr_section.temp_start.strftime("%I:%M %p") %>-<%= curr_section.temp_end.strftime("%I:%M %p") %></h4></li>
                        <% end %>
                      </ul>

                        <% badge_button = '<i class="fa fa-person"></i> '.html_safe + getPendingBadge(enroll).html_safe + ' View Attendance'%>

                        <% if section.jenroll == nil %>
                          <%= link_to badge_button.html_safe, senior_mentor_attendance_path(section.senroll), :class => "btn btn-info" %>
                          <%= link_to '<i class="fa fa-search"></i> View Roster'.html_safe, senroll_roster_path(section.senroll), :class => "btn btn-primary" %>  
                          <%= link_to '<i class="fa fa-exchange"></i> Switch Sections'.html_safe, senroll_switch_path(section.senroll.id), class: "btn btn-warning" %>
                          <%= link_to '<i class="fa fa-cog"></i> Mentor Settings'.html_safe, edit_senroll_path(section.senroll.id), class: "btn btn-success" %>
                        <% else %>
                          <%= link_to badge_button.html_safe, junior_mentor_attendance_path(section.jenroll), :class => "btn btn-info" %>
                          <%= link_to '<i class="fa fa-search"></i> View Roster'.html_safe, jenroll_roster_path(section.jenroll), :class => "btn btn-primary" %>
                          <%= link_to '<i class="fa fa-exchange"></i> Switch Sections'.html_safe, jenroll_switch_path(section.jenroll.id), class: "btn btn-warning" %>
                          <%= link_to '<i class="fa fa-cog"></i> Mentor Settings'.html_safe, edit_jenroll_path(section.jenroll.id), class: "btn btn-success" %>
                         <% end %>
                      </div> <!-- panel-body -->
                    </div> <!-- panel panel-primary -->
                  </div> <!-- section collapse -->
                </td>
              <% end %>
            </tr>  
          <% end %> <!-- enroll -->
        <% end %> <!-- section -->
      </tbody>
    </table>
  </div>
</div>

app/views/admins/mentor_index.html.erb
<div class = "container">
    <h1>Manage Mentors</h1>
    <hr>
    <div style = "margin-top:10px">
        <b>Total mentors</b>: <%= @mentors.length %>
    </div>
    <div class = "sections">
      <table class="table">
        <thead>
          <tr>
            <th> Actions </th>
            <th> Mentors </th>
          </tr>
        </thead>
        <tbody>
            <% @mentors.each do |mentor| %>
                <tr class="mentor-list">
                <td class="col-md-2">
                <div>
                <a class="btn btn-success" data-toggle="collapse" href="#rostercollapse<%=mentor.id%>"  href="#" role="button"><i class="fa fa-list"></i></a> <a class="btn btn-warning"  data-toggle="collapse" href="#editcollapse<%=mentor.id%>"  role="button"><i class="fa fa-dashboard"></i></a>
                </div>
                <div style="margin-top:5px">
                
                <%= link_to '<span class="btn btn-info" href="#" role="button"><i class="fa fa-user"></i></span>'.html_safe, admin_edit_student_path(mentor), method: :get %>
                <%= link_to '<span style="padding-right:15px"class="btn btn-danger" href="#" role="button"><i class="fa fa-times"></i></span>'.html_safe, admin_destroy_user_path(mentor), method: :delete, data: { confirm: "Are you sure you want to delete #{mentor.name}?" } %>
                </div>
                </td>
                <td>
                <h4 style="">
                 <%= mentor.name %>
                 </h4>
                
                <%= mentor.email %>

                <%= form_tag admin_add_course_path(mentor) do %>
                <br />
                <div class="collapse" id="rostercollapse<%=mentor.id%>">
                    <% mentor.jenrolls.each do |enroll| %>
                        <% section = enroll.section %>
                        <% course = enroll.course %>
                        <% if section != nil %>
                          <div class = "roster">
                              <h5><b><%= course.course_name %> <%= section.name %> Students</b></h5>
                              <% if enroll.getStudents().size > 0 %>
                                  <ul class="list-group">
                                  <% enroll.getStudents().each do |student| %>
                                    <li class="list-group-item" style="width: 75%">
                                      <span class="badge"><%=student.email%></span>
                                      <%=student.name %>
                                    </li>
                                  <% end %>
                                  </ul>                                    
                              <% else %>
                                  <h6>No Students</h6>
                              <% end %>
                          </div>
                        <% end %>
                    <% end %>
                    <% mentor.senrolls.each do |enroll| %>
                        <% section = enroll.section %>
                        <% course = enroll.course %>
                        <div class = "roster">
                            <h5><b><%= course.course_name %> <%= section.name %> Students</b></h5>
                            <% if enroll.getStudents().size > 0 %>
                                <ul class="list-group">
                                <% enroll.getStudents().each do |student| %>
                                  <li class="list-group-item" style="width: 75%">
                                    <span class="badge"><%=student.email%></span>
                                    <%=student.name %>
                                  </li>
                                <% end %>
                                </ul>                                    
                            <% else %>
                                <h6>No Students</h6>
                            <% end %>
                        </div>
                    <% end %>
                <% end %>
                </div>
                </div>
                <div class="collapse" id="editcollapse<%=mentor.id%>">
                    <%
                        senrolls = mentor.senrolls
                        jenrolls = mentor.jenrolls
                        courses_to_mentor_enrolls = Hash.new([])
                        jenrolls.each do |jenroll|
                            curr_class_name = Course.find(jenroll.course_id).course_name
                            courses_to_mentor_enrolls[curr_class_name] = courses_to_mentor_enrolls[curr_class_name] + [jenroll]
                        end
                        senrolls.each do |senroll|
                            curr_class_name = Course.find(senroll.course_id).course_name
                            courses_to_mentor_enrolls[curr_class_name] = courses_to_mentor_enrolls[curr_class_name] + [senroll]
                        end
                    %>
                    <% courses_to_mentor_enrolls.keys.sort.each do |course_name| %>
                      <div class="panel panel-primary" style="width: 80%">
                        <div class="panel-heading">
                          <h3 class="panel-title"><i class="fa fa-book"></i> <%= course_name %> 
                          </h3>

                        </div>
                        <div class="panel-body">
                          <% courses_to_mentor_enrolls[course_name].each do |enroll| %>
                            <% curr_section = Section.find(enroll.section_id) %>
                            <h4>  <%= link_to curr_section.name, section_path(curr_section) %></h4>
                            <ul class="list-unstyled">        
                            <li><b>Mentor:</b> <%= curr_section.getMentorName() %> (<%= mail_to curr_section.getMentorEmail() %>) </li>
                            <% if curr_section.temp_location == nil %>
                              <li><b>Location:</b> <%= curr_section.location %> </li>
                            <% elsif curr_section.temp_location == curr_section.location %>
                              <li><h4 style = "color:red;"><b>PERMANENT LOCATION:</b> <%= curr_section.location %></h4></li>
                            <% else %>
                              <li><h4 style = "color:red;"><b>TEMPORARY LOCATION:</b> <%= curr_section.temp_location %></h4></li>
                            <% end %>
                            <% if curr_section.temp_start == nil %>
                                <li><b>Time:</b> <%=curr_section.date %> <%= curr_section.start.strftime("%I:%M %p") %>-<%= curr_section.end.strftime("%I:%M %p") %> </li>
                            <% elsif curr_section.temp_start == curr_section.start and curr_section.temp_end == curr_section.end and curr_section.temp_date == curr_section.date %>
                                <li><h4 style = "color:red;"><b>PERMANENT TIME:</b> <%=curr_section.date %> <%= curr_section.start.strftime("%I:%M %p") %>-<%= curr_section.end.strftime("%I:%M %p") %></h4></li>
                            <% else %>
                                <li><h4 style = "color:red;"><b>TEMPORARY TIME:</b> <%=curr_section.temp_date %> <%= curr_section.temp_start.strftime("%I:%M %p") %>-<%= curr_section.temp_end.strftime("%I:%M %p") %></h4></li>
                            <% end %>
                            </ul>
                            <% badge_button = '<i class="fa fa-person"></i> '.html_safe + getPendingBadge(enroll).html_safe + ' View Attendance'%>       
                            <% if enroll.is_a?(Senroll) %>
                              <%= link_to badge_button.html_safe, senior_mentor_attendance_path(enroll), :class => "btn btn-info" %>
                              <%= link_to '<i class="fa fa-search"></i> View Roster'.html_safe, senroll_roster_path(enroll), :class => "btn btn-primary" %>  
                              <%= link_to '<i class="fa fa-exchange"></i> Switch Sections'.html_safe, senroll_switch_path(enroll.id), class: "btn btn-warning" %>
                              <%= link_to '<i class="fa fa-trash-o"></i> Drop Mentoring Section'.html_safe, enroll, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure you want to stop mentoring #{curr_section.name}?"}%>
                              <%= link_to '<i class="fa fa-cog"></i> Mentor Settings'.html_safe, edit_senroll_path(enroll.id), class: "btn btn-success" %>
                            <% else %>
                              <%= link_to badge_button.html_safe, junior_mentor_attendance_path(enroll), :class => "btn btn-info" %>
                              <%= link_to '<i class="fa fa-search"></i> View Roster'.html_safe, jenroll_roster_path(enroll), :class => "btn btn-primary" %>
                              <%= link_to '<i class="fa fa-exchange"></i> Switch Sections'.html_safe, jenroll_switch_path(enroll.id), class: "btn btn-warning" %>
                              <%= link_to '<i class="fa fa-trash-o"></i> Drop Mentoring Section'.html_safe, enroll, class: "btn btn-danger", method: :delete, data: { confirm: "Are you sure you want to stop mentoring #{curr_section.name}?"}%>
                              <%= link_to '<i class="fa fa-cog"></i> Mentor Settings'.html_safe, edit_jenroll_path(enroll.id), class: "btn btn-success" %>
                             <% end %>
                          <% end %>
                        </div>
                      </div>
                    <% end %>
                </div>
                </td>
                </tr>  
            <% end %>
        </tbody>
        </table>
    </div>
</div>