config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :registrations => "registrations" }
  root "homes#index"
  resources :courses

  get "/attendances" => "attendances#index", as: :student_attendance_index
  post "/attendances" => "attendances#create", as: :student_attendance_create
  post "/attendances/checkin" => "attendances#checkin", as: :student_attendance_checkin
  patch "/attendances/mentor/set_pass/:id" => "attendances#set_pass", as: :mentor_set_pass
  patch "/attendances/mentor/assign_attendance" => "attendances#set_status", as: :mentor_set_attendance_status
  patch "/attendances/mentor/batch_assign_attendance" => "attendances#batch_set_status", as: :mentor_batch_set_attendance_status
  patch "/attendances/mentor/approve_all" => "attendances#approve_all", as: :mentor_approve_all
  post "/attendances/mentor/assign_attendance" => "attendances#set_status"
  post "/attendances/mentor/approve_absence/:id" => "attendances#approve", as: :mentor_attendance_approve
  post "/attendances/mentor/reject_absence/:id" => "attendances#reject", as: :mentor_attendance_reject
  get "/attendances/mentor" => "attendances#mentor_index", as: :mentor_attendance_index
  get "/attendances/jmentor/:id" => "attendances#mentor_show", as: :junior_mentor_attendance
  get "/attendances/smentor/:id" => "attendances#mentor_show_senior", as: :senior_mentor_attendance
  get "/attendances/:id" => "attendances#show", as: :student_attendance

  resources :sections
  get "/sections/make-switch/:old_id/:new_id" => "sections#make_switch", as: :make_switch
  get "/sections/drop/:enroll_id" => "sections#drop", as: :drop_section

  resources :enrollments
  post "/enrollments/new" => "enrollments#create"
  patch "/enrollments/:id/edit" => "enrollments#update"
  delete "/enrollments/delete/:id" => "enrollments#destroy_admin", as: :admin_destroy_enroll
  get "/offers/:id" => "offers#show", as: :offer
  get "/new_offer" => "offers#new", as: :new_offer
  post "/offers" => "offers#create"
  delete "/offers/delete/enrollment/:id" => "offers#destroy", as: :delete_offer
  post "/create_response" => "offers#create_response", as: :create_response
  get "/enrollments/:id/switch-section" => "enrollments#switch_section", as: :switch_section

  delete "/comments/:id" => "comments#destroy", as: :delete_comment
  delete "/replies/:id" => "replies#destroy", as: :delete_reply
  post "/replies/accept/:id" => "replies#accept", as: :accept_reply
  post "/replies/deny/:id" => "replies#deny", as: :deny_reply

  get "/users/contract/:id" => "users#contract", as: :contract
  post "/users/sign-contract/:id" => "users#sign_contract", as: :sign_contract

  resources :jenrolls
  post "/jenrolls/mentorenrollredirect" => "jenrolls#mentor_enroll_redirect", as: :mentor_enroll_redirect
  get "/jenrolls/mentorenroll/:course_id" => "jenrolls#mentor_enroll", as: :mentor_enroll
  post "/jenrolls/new" => "jenrolls#create"
  patch "/jenrolls/:id/edit" => "jenrolls#update"
  get "/jenrolls/:id/switch" => "jenrolls#switch", as: :jenroll_switch
  patch "/jenrolls/:id/switch" => "jenrolls#update_switch", as: :jenroll_update_switch
  get "/jenrolls/:id/roster" => "jenrolls#roster", as: :jenroll_roster
  delete "/jenrolls/:id/templocation" => "jenrolls#destroy_temp_location", as: :jenroll_destroy_temp_location
  delete "/jenrolls/:id/temptime" => "jenrolls#destroy_temp_time", as: :jenroll_destroy_temp_time

  resources :senrolls
  patch "/senrolls/:id/edit" => "senrolls#update"
  get "/senrolls/:id/switch" => "senrolls#switch", as: :senroll_switch
  patch "/senrolls/:id/switch" => "senrolls#update_switch", as: :senroll_update_switch
  get "/senrolls/:id/roster" => "senrolls#roster", as: :senroll_roster
  delete "/senrolls/:id/templocation" => "senrolls#destroy_temp_location", as: :senroll_destroy_temp_location
  delete "/senrolls/:id/temptime" => "senrolls#destroy_temp_time", as: :senroll_destroy_temp_time

  match "/admin/students" => "admins#index", as: :students_index, via: [:get, :post]
  get "/admin/mentors" => "admins#mentor_index", as: :mentors_index
  get "/admin/new-student" => "admins#new_student", as: :admin_new_student
  post "/admin/create-student" => "admins#create_student", as: :admin_create_student
  get "/admin/students/:id" => "admins#edit_student", as: :admin_edit_student
  patch "/admin/students/:id" => "admins#update_student", as: :admin_update_student
  post "/admin/students/add_course/:user_id" => "admins#add_course", as: :admin_add_course
  get "/admin/courses" => "courses#admin_index", as: :admin_course_index
  post "/admin/send_email" => "admins#send_email", as: :admin_send_email
  get "/settings" => "settings#index",  as: :settings
  post "/settings" => "settings#update"
  get "/admin/manage_sections" => "admins#manage_sections", as: :manage_sections
  get "/admin/manage_attendance" => "admins#manage_attendance", as: :manage_attendance
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  get "/settings/announcement_edit" => "announcements#edit", as: :announcement_edit
  patch "/settings/announcement_edit" => "announcements#update", as: :announcement_update
  
  get "/admin/manage_section/add/:id" => "admins#new_student_to_section", as: :new_student_to_section
  post "/admin/manage_section/add/:id" => "admins#add_student_to_section"
  post "/admin/manage_sections/drop/:id" => "admins#drop_student_from_section", as: :drop_student_from_section

end

app/controllers/enrollments_controller.rb
class EnrollmentsController < ApplicationController
  before_filter :check_logged_in
  before_filter :check_switch_section, :only => [:switch_section]

  # Creating an enrollment enrolls you into a class
  # Editing an enrollment's section_id enroll you into a section

	def switch_section
		#enrollment works here
		@enrollment = Enroll.find(params[:id])
		@section = Section.find(@enrollment.section_id)
		@course = Course.find(@enrollment.course_id)
		@open_sections = @section.getOtherOpenSections()
		@offer = @enrollment.offer
		@compatable_offers = Offer.getCompatableOffers(@section)
		@transactions = @enrollment.getTransactionsInReverseOrder
    @section_limit = @section.getLimit()
	end

  def new
    @enrollment = Enroll.new
    @courses = Course.all
  end

  def create
    course = Course.find_by_course_name(params[:enroll][:course_id])

    #check if the student has already been enrolled in the class
    @enrolls = current_user.enrolls
    @enrolls.each do |enroll|
      if enroll.course_id == course.id
        flash[:notice] = "You are already enrolled into this class"
        redirect_to new_enrollment_path
        return
      end
    end  

    @enrollment = Enroll.new
    course = Course.find_by_course_name(params[:enroll][:course_id])
    @enrollment.user_id = current_user.id
    @enrollment.course_id = course.id
    if @enrollment.save
      flash[:notice] = "You have been enrolled into #{course.course_name}"
      redirect_to root_path
    else
      render :action => 'new'
    end
  end

  def edit
    @enrollment = Enroll.find(params[:id])

    #check that current user isn't editing an enrollment he/she doesn't own
    if @enrollment.user_id != current_user.id
      flash[:notice] = "Forbbiden access. Use the switch section button to change sections"
      redirect_to root_path
      return
    end

    @sections = { "Monday" => [], "Tuesday" => [], "Wednesday" => [], 
        "Thursday" => [], "Friday" => [] }
    course = Course.find(@enrollment.course_id)

    course.sections.each do | section |
      @sections[section.getDay] << section
    end
    @sections["Monday"].sort!{|a,b| a.start && b.start ? a.start <=> b.start : a.start ? -1 : 1 }
    @sections["Tuesday"].sort!{|a,b| a.start && b.start ? a.start <=> b.start : a.start ? -1 : 1 }
    @sections["Wednesday"].sort!{|a,b| a.start && b.start ? a.start <=> b.start : a.start ? -1 : 1 }
    @sections["Thursday"].sort!{|a,b| a.start && b.start ? a.start <=> b.start : a.start ? -1 : 1 }
    @sections["Friday"].sort!{|a,b| a.start && b.start ? a.start <=> b.start : a.start ? -1 : 1 } 
  end

  def update
    if not params[:enroll]
      flash[:notice] = "You need to select a section"
      redirect_to edit_enrollment_path(params[:id])
      return
    end
    section = Section.find(params[:enroll][:section_id])
    enrollment = Enroll.find(params[:id])

    #check if section isn't full
    if section.enrolls.size >= section.getLimit()
      flash[:notice] = "Current section you selected has been filled up."
      redirect_to edit_enrollment_path(params[:id])
      return
    end

    #check if student already enrolled into this section
    curr_enrolls = section.enrolls.to_ary()
    current_user.enrolls.each do |enroll|
      if curr_enrolls.include?(enroll)
        flash[:notice] = "You are already enrolled into this section"
        redirect_to root_path
        return
      end
    end

    #check if student is already enrolled into another section in the same class
    if not enrollment.section_id.nil?
      flash[:notice] = "You are already enrolled into another section in this class"
      redirect_to root_path
      return
    end

    #safe to enroll
    enrollment.section_id = section.id
    section.enrolls << enrollment
    if enrollment.save! and section.save!
      flash[:notice] = "You have signed up for #{section.name}"
      redirect_to root_path
      return
    else
      flash[:notice] = "Couldn't sign up for section. Try again"
      redirect_to root_path
      return
    end
  end

  def destroy
    @enrollment = Enroll.find(params[:id])
    @course = Course.find(@enrollment.course_id)
    flash[:notice] = "You have been dropped from #{@course.course_name}"
    @enrollment.removeAllReplies
    @enrollment.destroy
    redirect_to root_path
  end

  def destroy_admin
    @enroll = Enroll.find(params[:id])
    @user = User.find(@enroll.user_id)
    @course = Course.find(@enroll.course_id)
    @enroll.destroy
    flash[:notice] = "#{@user.name} has been dropped from #{@course.course_name}"
    redirect_to students_index_path
  end


  #**************************************************************************
  #before_filters
  private
  def check_switch_section
    #check if enrollment is fine
    correct_enrollment = false
    if params[:id] and Enroll.exists?(params[:id]) and check_enrollment(enroll = Enroll.find(params[:id]))
      correct_enrollment = true
    end
    #checks if section is fine
    correct = false
    if correct_enrollment and enroll.hasSection
      correct = true
    end
    if not correct
      flash[:notice] = "You are not allowed access to that page."
      redirect_to root_path
    end
  end
end

app/helpers/enrollments_helper.rb
module EnrollmentsHelper
end

app/views/enrollments/edit.html.erb
<h3>Choose a section</h3>
<%= form_for @enrollment, url: edit_enrollment_path do |f| %>

      <table class="table">
        <thead>
          <tr>
            <th>  </th>
            <th> Section # </th>
            <th> Day </th>
            <th> Time </th>
            <th> # Enrolled </th>
            <th> Mentor </th>
            <th> Location </th>
          </tr>
        </thead>
        <tbody>
        <% counter = 0%>
          <% @sections.each do | day, sections |%>
            <% sections.each do |section| %>
              <% section_limit = section.getLimit() %>
                <% if not section.isFull %>
                <% counter += 1%>
                <tr >
                  <% if section.enrolls.size >= section_limit %>
                    <td> <%= f.radio_button :section_id, section.id, :disabled => true %> </td>
                  <% else %>
                    <td> <%= f.radio_button :section_id, section.id %> </td>
                  <% end %>
                  <td> <%= section.name %> </td>
                  <td> <%= section.date %> </td>
                  <td> <% if section.start and section.end %>
                    <%= section.start.strftime("%I:%M %p") %>-<%= section.end.strftime("%I:%M %p") %>
                    <% end %> </td>
                  <td> <%= section.enrolls.size %> out of <%= section_limit %> </td>
                  <td> <%= section.getMentorName() %> </td>
                  <td> <%= section.location %> </td>
                </tr>
                <% end %>
            <% end %>
          <% end %>
          <% if counter == 0 %>
            There are no sections available. Check back tomorrow, and there might be room!
          <% end %>
        </tbody>
      </table>
  <% if counter > 0 %>
  <%= f.submit "Add section", class: "btn btn-success" %>
  <% end %>
<% end %>

app/views/enrollments/new.html.erb
<h3>Choose a course</h3>
<%= form_for @enrollment, url: new_enrollment_path do |f| %>

  <table class="table">
    <thead>
      <tr>
        <th>  </th>
        <th> Course Name </th>
        <th> Semester </th>
      </tr>
    </thead>
    <tbody>
      <% @courses.each do |course| %>
        <tr>
          <td> <%= f.radio_button :course_id, course.course_name %> </td>
          <td> <%= course.course_name %> </td>
          <td> <%= course.semester %> <%= course.year %> </td>
        </tr>
      <% end %>
    </tbody>
  </table>

  <%= f.submit "Add course", class: "btn btn-success" %>
<% end %>

app/views/enrollments/switch_section.html.erb
<ul class="nav nav-tabs nav-justified" style = "padding-top: 50px">
  <li class="active"><a data-toggle="tab" href="#open-sections"><i class = "fa fa-cart-plus"></i> Open Sections</a></li>
  <li><a data-toggle="tab" href="#trade-section"><i class = "fa fa-arrows-h"></i> Trade</a></li>
  <li><a data-toggle="tab" href="#transactions"><i class = "fa fa-money"></i> Transactions</a></li>
</ul>

<div class="tab-content">
  <div id="open-sections" class="tab-pane fade in active">
  	<!-- open sections section -->
    
	<h2>Open Sections</h2>
  	<div class = "row">
  		<div class = "col-md-12">
			<div class="panel-group" id="accordion">
				<div class="list-group">
					<% @open_sections.each_with_index do |section, index|%>
						<% studentCount = section.getStudentCount %>
						  <div class="list-group-item">
						    <h4 class="list-group-item-heading"><%= section.name %></h4>
						    <div class="progress">
							  <div class="progress-bar" role="progressbar" aria-valuenow="60" aria-valuemin="0" aria-valuemax="100" style="width: <%= (studentCount * (100/@section_limit))%>%;">
							  	<% if studentCount >= 0 %>
							    	<%=studentCount%>/<%= @section_limit%>
							    <% end %>
							  </div>
							</div>
							<div>
								Where: <% if section.location %>
										<%=section.location %> 
										<% else %>
										TBD
										<%end%>
							</div>
							<div>
								When: <% if section.start and section.end and section.date%>
											<%= section.start.strftime("%I:%M %p")%> to <%= section.end.strftime("%I:%M %p")%> on <%= section.date%>
										<% else %>
											TBD
										<% end %>
							</div>
							<div>
								Mentor: <% if section.getMentor() %> 
											<%= section.getMentorName() %>
										<% else %>
											TBD
										<% end %>
							</div>
							<%= link_to "See Section", section_path(section), :class =>"btn btn-primary" %>
							<%= link_to "Switch", make_switch_path(old_id: @enrollment.section_id, new_id: section.id, enroll_id: @enrollment.id), :class =>"btn btn-success" %>
						  </div>
					<% end %>
				</div>
			</div>
		</div>
	</div>
	<% if @open_sections.length == 0 %>
		<h4>No open sections for this course.</h4>
	<% end %>
  </div>


  <div id="trade-section" class="tab-pane fade">
  	<br>
  	<!-- trade section -->
  	<div class = "row">
  		<div class = "your-offer col-md-12">
  			<div class="panel panel-primary" style = "text-align:center">
			  <div class="panel-heading">
			    <h1 class="panel-title">Your Offer for Section <%= @section.name %></h1>
			  </div>
			  <div class="panel-body">
			  	<% if @offer %>
					<div class="well well-sm">View your offer to see if anyone with the sections you want is willing to switch.</div>
					<%= link_to "View Offer", offer_path(@offer), :class => "btn btn-info" %>
					<%= link_to "Cancel Offer", delete_offer_path(@enrollment), method: :delete, :class => "btn btn-danger"  %>
				<% else %>
					<div class="well well-sm">Create an offer and specify any sections you would want in return.</div>
					<label>No offer exists.</label><br>
					<%= link_to "Create One?", new_offer_path(enroll_id: @enrollment.id), :class => "btn btn-success"%>
				<% end %>
			  </div>
			</div>
		</div>
  	</div>
  	<div class = "row">
  		<div class = "other-offers col-md-12">
  			<div class="panel panel-success">
			  <!-- Default panel contents -->
			  <div class="panel-heading" style = "text-align:center"><h1 class="panel-title">See Other Available Trading Offers</h1></div>
			  <div class="panel-body" style = "text-align:center; padding-bottom:0px">
				<div class="well well-sm">You can leave a comment on any of these offers, or ask to switch. Note that only offers that want your section will appear.</div>
			    <% if @compatable_offers.length == 0 %>
					<label>No offers exist that want your section.</label>
				<% end %>
			  </div>

			  <!-- List group -->
				<div class="list-group">
					<% @compatable_offers.each do |offer|%>
						<% section = Section.find(offer.section_id) %>
						<% html = "<span class='badge'>" + offer.created_at.strftime("%I:%M:%S %p on %b. %d, %Y") + "</span><h4 class='list-group-item-heading'>Offer for " << section.name + "</h4><p class='list-group-item-text'>" + offer.body + "</p>" %>
						<%= link_to raw(html), offer_path(offer), :class => "list-group-item" %>
					<% end %>
				</div>

			</div>
  		</div>
  		
  	</div>
  </div>
  <div id="transactions" class="tab-pane fade">
  	<h2>Transactions</h2>
  	<% @transactions.each do |t| %>
	  	<div class="panel panel-default">
		  <div class="panel-body">
		    <%=t.body%>
		  </div>
		  <div class="panel-footer"><%= t.created_at.strftime("%I:%M:%S %p on %b. %d, %Y")%></div>
		</div>
  	<% end %>
  	<% if @transactions.length == 0 %>
  		<h4>No transactions.</h4>
  	<% end %>
  </div>
</div>