config/routes.rb
Rails.application.routes.draw do

  mount Ckeditor::Engine => '/ckeditor'

  devise_for :users, :controllers => { :registrations => "registrations" }
  root "homes#index"
  resources :courses

  get "/attendances" => "attendances#index", as: :student_attendance_index
  post "/attendances" => "attendances#create", as: :student_attendance_create
  post "/attendances/checkin" => "attendances#checkin", as: :student_attendance_checkin
  patch "/attendances/mentor/set_pass/:id" => "attendances#set_pass", as: :mentor_set_pass
  patch "/attendances/mentor/assign_attendance" => "attendances#set_status", as: :mentor_set_attendance_status
  patch "/attendances/mentor/batch_assign_attendance" => "attendances#batch_set_status", as: :mentor_batch_set_attendance_status
  patch "/attendances/mentor/approve_all" => "attendances#approve_all", as: :mentor_approve_all
  post "/attendances/mentor/assign_attendance" => "attendances#set_status"
  post "/attendances/mentor/approve_absence/:id" => "attendances#approve", as: :mentor_attendance_approve
  post "/attendances/mentor/reject_absence/:id" => "attendances#reject", as: :mentor_attendance_reject
  get "/attendances/mentor" => "attendances#mentor_index", as: :mentor_attendance_index
  get "/attendances/jmentor/:id" => "attendances#mentor_show", as: :junior_mentor_attendance
  get "/attendances/smentor/:id" => "attendances#mentor_show_senior", as: :senior_mentor_attendance
  get "/attendances/:id" => "attendances#show", as: :student_attendance

  resources :sections
  get "/sections/make-switch/:old_id/:new_id" => "sections#make_switch", as: :make_switch
  get "/sections/drop/:enroll_id" => "sections#drop", as: :drop_section

  resources :enrollments
  post "/enrollments/new" => "enrollments#create"
  patch "/enrollments/:id/edit" => "enrollments#update"
  delete "/enrollments/delete/:id" => "enrollments#destroy_admin", as: :admin_destroy_enroll
  get "/offers/:id" => "offers#show", as: :offer
  get "/new_offer" => "offers#new", as: :new_offer
  post "/offers" => "offers#create"
  delete "/offers/delete/enrollment/:id" => "offers#destroy", as: :delete_offer
  post "/create_response" => "offers#create_response", as: :create_response
  get "/enrollments/:id/switch-section" => "enrollments#switch_section", as: :switch_section

  delete "/comments/:id" => "comments#destroy", as: :delete_comment
  delete "/replies/:id" => "replies#destroy", as: :delete_reply
  post "/replies/accept/:id" => "replies#accept", as: :accept_reply
  post "/replies/deny/:id" => "replies#deny", as: :deny_reply

  get "/users/contract/:id" => "users#contract", as: :contract
  post "/users/sign-contract/:id" => "users#sign_contract", as: :sign_contract

  resources :jenrolls
  post "/jenrolls/mentorenrollredirect" => "jenrolls#mentor_enroll_redirect", as: :mentor_enroll_redirect
  get "/jenrolls/mentorenroll/:course_id" => "jenrolls#mentor_enroll", as: :mentor_enroll
  post "/jenrolls/new" => "jenrolls#create"
  patch "/jenrolls/:id/edit" => "jenrolls#update"
  get "/jenrolls/:id/switch" => "jenrolls#switch", as: :jenroll_switch
  patch "/jenrolls/:id/switch" => "jenrolls#update_switch", as: :jenroll_update_switch
  get "/jenrolls/:id/roster" => "jenrolls#roster", as: :jenroll_roster
  delete "/jenrolls/:id/templocation" => "jenrolls#destroy_temp_location", as: :jenroll_destroy_temp_location
  delete "/jenrolls/:id/temptime" => "jenrolls#destroy_temp_time", as: :jenroll_destroy_temp_time

  resources :senrolls
  patch "/senrolls/:id/edit" => "senrolls#update"
  get "/senrolls/:id/switch" => "senrolls#switch", as: :senroll_switch
  patch "/senrolls/:id/switch" => "senrolls#update_switch", as: :senroll_update_switch
  get "/senrolls/:id/roster" => "senrolls#roster", as: :senroll_roster
  delete "/senrolls/:id/templocation" => "senrolls#destroy_temp_location", as: :senroll_destroy_temp_location
  delete "/senrolls/:id/temptime" => "senrolls#destroy_temp_time", as: :senroll_destroy_temp_time

  match "/admin/students" => "admins#index", as: :students_index, via: [:get, :post]
  get "/admin/mentors" => "admins#mentor_index", as: :mentors_index
  get "/admin/new-student" => "admins#new_student", as: :admin_new_student
  post "/admin/create-student" => "admins#create_student", as: :admin_create_student
  get "/admin/students/:id" => "admins#edit_student", as: :admin_edit_student
  patch "/admin/students/:id" => "admins#update_student", as: :admin_update_student
  post "/admin/students/add_course/:user_id" => "admins#add_course", as: :admin_add_course
  get "/admin/courses" => "courses#admin_index", as: :admin_course_index
  post "/admin/send_email" => "admins#send_email", as: :admin_send_email
  get "/settings" => "settings#index",  as: :settings
  post "/settings" => "settings#update"
  get "/admin/manage_sections" => "admins#manage_sections", as: :manage_sections
  get "/admin/manage_attendance" => "admins#manage_attendance", as: :manage_attendance
  match 'users/:id' => 'users#destroy', :via => :delete, :as => :admin_destroy_user

  get "/settings/announcement_edit" => "announcements#edit", as: :announcement_edit
  patch "/settings/announcement_edit" => "announcements#update", as: :announcement_update
  
  get "/admin/manage_section/add/:id" => "admins#new_student_to_section", as: :new_student_to_section
  post "/admin/manage_section/add/:id" => "admins#add_student_to_section"
  post "/admin/manage_sections/drop/:id" => "admins#drop_student_from_section", as: :drop_student_from_section

end

app/models/course.rb
class Course < ActiveRecord::Base
  has_many :enrolls, dependent: :destroy
  has_many :sections, dependent: :destroy
  has_many :jenrolls, dependent: :destroy
  has_many :senrolls, dependent: :destroy
end

app/models/offer.rb
class Offer < ActiveRecord::Base
  belongs_to :user
  belongs_to :section
  belongs_to :enroll
  has_many :replies, dependent: :destroy
  has_many :wants, dependent: :destroy
  has_many :comments, dependent: :destroy

  def getCommentsInReverseOrder()
  	return self.comments.order(:created_at).reverse_order
  end

  def getRepliesInOrder()
    return self.replies.order(:created_at)
  end

  def getEnrollmentOfOfferer()
    return Enroll.find(self.enroll_id)
  end

  def hasReplyFrom(enroll)
    self.replies.each do |r|
      if r.getEnrollmentOfReplier.id = enroll.id
        return true
      end
    end
    return false
  end
  def getReplyFrom(enroll)
    self.replies.each do |r|
      if r.getEnrollmentOfReplier.id = enroll.id
        return r
      end
    end
    return nil
  end

  def self.getCompatableOffers(current_section)
    compatable_offers = []
    current_section.wants.each do |want|
      compatable_offers << Offer.find(want.offer_id)
    end
    return compatable_offers
  end

  def getWantedSections()
    wanted_sections = []
    self.wants.each do |want|
      wanted_sections << Section.find(want.section_id)
    end
    return wanted_sections
  end

  def createWants(section_ids)
    section_ids.each do |id|
      curr_want = Want.create(section_id: id)
      self.wants << curr_want
    end
  end
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
	before_filter :check_logged_in
	before_filter :check_create_response, :only => [:create_response]
	before_filter :check_show, :only => [:show]
	before_filter :check_new, :only => [:new]
	before_filter :check_create, :only => [:create]
	before_filter :check_destroy, :only => [:destroy]
	def show
		@offer = Offer.find(params[:id])
		@offerer = User.find(@offer.user_id)
		@section = Section.find(@offer.section_id)
		@course = Course.find(@section.course_id)
		@enroll = current_user.getEnrollmentInCourse(@course)
		@wanted_sections = @offer.getWantedSections
		@comments = @offer.comments.order(:created_at).reverse_order
		@new_comment = Comment.new
		@replies = @offer.replies.order(:created_at)
		@new_reply = Reply.new
		@comments_allowed = Setting.find_by(name: 'comments').value == "1"
	end
	def new
		#needs to check whether or not user has an offer
		@enrollment = Enroll.find(params[:enroll_id])
		@section = Section.find(@enrollment.section_id)
		@other_sections = @section.getAllOtherSections
		@new_offer = Offer.new(:section_id => @section.id, :user_id => current_user.id, :enroll_id => @enrollment.id)
	end
	def create
		#@enroll is enrollment
		@offer = Offer.new(offer_params)
		@enroll = @offer.getEnrollmentOfOfferer
		@offerer = User.find(@enroll.user_id)
		@offerer_section = Section.find(@enroll.section_id)
		@offerer.offers << @offer
		@offerer_section.offers << @offer
		if @offer.save
			section_ids = params[:section_ids]
			@offer.createWants(section_ids)
			flash[:notice] = "Created an offer for your section!"
			@offered_section = Section.find(@offer.section_id)
			@offer.getEnrollmentOfOfferer.createTransaction("You created an offer for " << @offered_section.name)
			redirect_to offer_path(@offer)
		end
	end
	def destroy
		@enroll = Enroll.find(params[:id])
		@offer = @enroll.offer
		if @offer
			if @offer.destroy
				flash[:notice] = "Canceled your offer for your section."
				@enroll.createTransaction("You canceled your offer for " << Section.find(@offer.section_id).name)
			else
				flash[:notice] = "Something went wrong with deleting your offer. Try again later."
			end
		else
			flash[:notice] = "You don't have an offer to cancel."
		end
		redirect_to switch_section_path(@enroll)
	end

	def create_response
		#needs to check if params[:switch] is there
		@body = params[:body]
		@offer = Offer.find(eval(params[:offer_id])[:value])
		@enroll = Enroll.find(eval(params[:enroll_id])[:value])
		if params[:switch]
			@reply = Reply.new(body: @body)
			@offer.replies << @reply
			@reply.user_id = current_user.id
			@reply.offer_id = @offer.id
			@replies = @offer.getRepliesInOrder
			@comments = @offer.getCommentsInReverseOrder
			respond_to do |format|
			    if @offer.save && @reply.save
			    	@reply.getEnrollmentOfReplier.createTransaction("You created a reply to an offer.")
			      format.js
			    else
			      # format.html { render action: "new" }
			      # format.json { render json: @user.errors, status: :unprocessable_entity }
			    end
			end
		else
			@comment = Comment.new(body: @body)
			@offer.comments << @comment
			@comment.user_id = current_user.id
			@comment.offer_id = @offer.id
			@replies = @offer.getRepliesInOrder
			@comments = @offer.getCommentsInReverseOrder
			respond_to do |format|
			    if @offer.save && @comment.save
			    	@comment.getEnrollmentOfCommenter.createTransaction("You created a comment to an offer.")
			      format.js
			    else
			      # format.html { render action: "new" }
			      # format.json { render json: @user.errors, status: :unprocessable_entity }
			    end
			end
		end
	end
	def error
		respond_to do |format|
		    format.js
		end
	end

	private
	def offer_params
		params.require(:offer).permit(:body, :enroll_id)
	end

	#**************************************************************************
  #before_filters
  private
  def check_show
  	#check if offer exists
  	notice = "The offer you are trying to view may have closed or does not exist."
  	correct_offer = false
  	if params[:id] and Offer.exists?(params[:id])
  		correct_offer = true
  	end
  	if correct_offer
  		notice = "You are not allowed access to that page."
  		#check if he is enrolled in the correct course
  		offer = Offer.find(params[:id])
		offerer = User.find(offer.user_id)
		section = Section.find(offer.section_id)
		course = Course.find(section.course_id)
		enroll = current_user.getEnrollmentInCourse(course)
		if check_enrollment(enroll) or current_user.admin
			return
		end
  	end
    flash[:notice] = notice
    redirect_to root_path
  end

  private
  def check_new
  	notice = "You are not allowed access to that page."
  	if params[:enroll_id] and Enroll.exists?(params[:enroll_id]) and check_enrollment(enroll = Enroll.find(params[:enroll_id]))
  		if enroll.hasSection
  			puts enroll.offer
  			if not enroll.offer
  				return
  			else 
  				notice = "You already have an offer."
  			end
  		end
  	end
  	flash[:notice] = notice
    redirect_to root_path
  end
  private
  def check_new
  	notice = "You are not allowed access to that page."
  	if params[:enroll_id] and Enroll.exists?(params[:enroll_id]) and check_enrollment(enroll = Enroll.find(params[:enroll_id]))
  		if enroll.hasSection
  			if not enroll.offer
  				return
  			else 
  				notice = "You already have an offer."
  			end
  		end
  	end
  	flash[:notice] = notice
    redirect_to root_path
  end
  private
  def check_create
  	notice = "You are not allowed to access that page."
  	path = root_path
  	if section_ids = params[:offer] and offer = Offer.new(offer_params)
  		if offer.enroll_id and check_enrollment(enroll = offer.getEnrollmentOfOfferer)
  			if params[:section_ids]
  				if not enroll.offer
	  				return
	  			end
  				notice = "You already have an offer."
  				path = offer_path(enroll.offer)
  			else
	  			notice = "You need to choose a section you want in your offer."
	  			path = new_offer_path(enroll_id: enroll.id)
  			end
  				
  		end
  	end
  	flash[:notice] = notice
  	redirect_to path
  end
  private
  def check_destroy
  	if not(params[:id] and Enroll.exists?(params[:id]) and check_enrollment(Enroll.find(params[:id])))
  		flash[:notice] = "You are not allowed to access that page."
  		redirect_to root_path
  	end
  end

  private
  def check_create_response
  	@notice = "You cannot create a comment."
  	if params[:offer_id] and params[:enroll_id]
  		if Offer.exists?(eval(params[:offer_id])[:value]) and Enroll.exists?(eval(params[:enroll_id])[:value])
  			offer = Offer.find(eval(params[:offer_id])[:value])
  			enroll = Enroll.find(eval(params[:enroll_id])[:value])
  			if check_enrollment(enroll)
  				if params[:switch]
  					if offer.hasReplyFrom(enroll)
  						@notice = "You have already made a reply to this offer."
  					else
  						if params[:body] == ""
  							@notice = "You cannot create a blank reply."
  						else
  							return
  						end	
  					end
  				else
  					if params[:body] == ""
						@notice = "You cannot create a blank comment."
					else 
						return
					end		
  				end
  			end
  		end
  	end
  	render "error"
  end

end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_add_response.html.erb
<%= form_tag(create_response_path, :remote => true) do |f| %>
	<div class = "field">
		<h4>Add Response</h4>
		<div class = "form-group">
			<%= text_area_tag :body, nil, :class => "form-control", :style => "height:100px" %>
		</div>
		<% if current_user.id != @offerer.id %>
			Want to switch? Check to add a reply! <%= check_box_tag "switch" %>
		<% end %>
		<%= hidden_field_tag :offer_id, :value => offer.id %>
		<% if enroll %>
			<%= hidden_field_tag :enroll_id, :value => enroll.id %>
		<% end %>
	</div>
	<div class = "actions" style = "margin-top: 10px">
		<%= button_tag(type: 'submit', class: "btn btn-success") do %>
		 <i class='fa fa-plus'></i> Add
		<% end %>
	</div>
<% end %>

app/views/offers/_comments_section.html.erb
<% comments.each do |comment|%>
	<div class = "media" style = "border: #ccc solid 1px; padding: 5px; border-radius: 3px;">
		<% if current_user.id == comment.user_id %>
			<div class="pull-right">
				<%= link_to "<i class='fa fa-remove' style = 'color:grey;'></i>".html_safe, delete_comment_path(comment), method: :delete, :remote => true, data: {confirm:"Are you sure you want to delete your comment?"} %>
			</div>
		<% end %>
		
		<div class="media-body">
			<h4 class="media-heading"><%= User.find(comment.user_id).name %><br><small><%= comment.created_at.strftime("%I:%M:%S %p on %b. %d, %Y") %></small></h4>
		    <%= comment.body %>
		   
		</div>
	</div>
<% end %>		

app/views/offers/_replies_section.html.erb
<% replies.each do |reply|%>
	<div class = "media" style = "border: #ccc solid 1px; padding: 5px; border-radius: 3px; background-color: #F0F8FF;">
		<% if current_user.id == reply.user_id %>
			<div class="pull-right">
				<%= link_to "<i class='fa fa-remove' style = 'color:grey;'></i>".html_safe, delete_reply_path(reply), method: :delete, :remote => true, data: {confirm:"Are you sure you want to delete your reply?"} %>
			</div>
		<% end %>
		
		<div class="media-body">
			<h4 class="media-heading"><%= User.find(reply.user_id).name %><br><small><%= reply.created_at.strftime("%I:%M:%S %p on %b. %d, %Y") %> | <%= Section.find(reply.getEnrollmentOfReplier.section_id).name %></small></h4>
		    <%= reply.body %>
		   	<% if current_user.id == Offer.find(reply.offer_id).user_id %>
		   		<div style = "margin-top: 10px">
		    		<%= link_to "<i class='fa fa-check'></i> Accept Reply".html_safe, accept_reply_path(reply), :class => "btn btn-success", method: "post", data: {confirm:"Are you sure you want to accept this reply? This will trade your section!"} %> <%= link_to "<i class='fa fa-ban'></i> Deny Reply".html_safe, deny_reply_path(reply), :class => "btn btn-danger", method: "post", data: {confirm:"Are you sure you want to decline this reply?"} %>
		    	</div>
		    <% end %>
		</div>
	</div>
<% end %>	

app/views/offers/create_response.js.erb
$("#comments").empty();
$("#comments").append("<%= escape_javascript(render partial:'offers/comments_section', locals: {comments: @comments}) %>");
$("#replies").empty();
$("#replies").append("<%= escape_javascript(render partial:'offers/replies_section', locals: {replies: @replies}) %>");
$("#add-response textarea").val("");

app/views/offers/error.js.erb
alert("<%= @notice %>");

app/views/offers/new.html.erb
<div class = "row" style = "padding-top: 50px">
	<div class = "col-md-12">
		<div class="panel panel-default">
		    <div class="panel-heading">Offer For Section <%= @section.name %></div>
		    <div class="panel-body">
		    <%= form_for @new_offer do |f|%>
		        <div class="form-group">
		        <label>Which Sections Are Okay To Switch With?</label>
		        <% @other_sections.each do |section| %>
					<label class = "checkbox-inline" ><%= check_box_tag 'section_ids[]', section.id %><%= section.name %></label>
				<% end %>
		        </div>
		        <div class="form-group">
		        <label>Anything to add?</label>
		        <%= f.text_area :body, :class => "form-control", :rows => 5 %>
		        </div>
		        <%= f.hidden_field :enroll_id, :value => @enrollment.id %>
		        <div class = "actions">
					<%= f.submit "Create Offer", class: "btn btn-default" %>
				</div>
		    <% end %>
		    </div>
		</div>
	</div>
</div>

app/views/offers/show.html.erb
<div class = "header col-xs-9 col-xs-offset-1">
	<h1>Offer For <%=  @section.name %></h1>
	<div class="panel panel-primary">
	  <div class="panel-heading">
	    <h3 class="panel-title"><%= User.find(@offer.user_id).name %> wants one of the following sections:</h3>
	  </div>
	  <ul class="list-group">
	  	<% @wanted_sections.each do |section| %>
	    	<li class="list-group-item"><%= section.name %></li>
	    <% end %>
	  </ul>
	  <div class="panel-body">
	  	<h3 style = "margin-top:0px;">Additional Info</h3>
	  	<div class = "body">
	  		<%= @offer.body %>
	  	</div>
	  </div>

	</div>
	<div id = "add-response">
		
		<% if @comments_allowed %>
			<%= render partial: "add_response.html", locals: {offer: @offer, enroll: @enroll} %>
		<% else %>
			<h4>Adding comments is currently disabled.</h4>
		<% end %>
	</div>
</div>


<div class = "row">
	<h2 class = "col-sm-6 col-xs-12" >Comments</h2>
	<h2 class = "col-sm-6 col-xs-12" >Replies</h2>
</div>
<hr>
<div class = "row">
	<div class = "col-sm-6 col-xs-12" id = "comments">
		<%= render partial: "comments_section.html", locals: {comments: @comments}%>
	</div>
	<div class = "col-sm-6 col-xs-12" id = "replies">
		<%= render partial: "replies_section.html", locals: {replies: @replies}%>
	</div>
</div>